name: Manual build and publish a container image

on:
  workflow_dispatch:
    inputs:
      baseImage:
        description: "Base image"
        required: true
        default: nvidia/cuda:11.8.0-runtime-ubuntu22.04
        type: choice
        options:
          - nvidia/cuda:11.8.0-runtime-ubuntu22.04
env:
  REGISTRY: ghcr.io
  REPO_NAME: ${{ github.repository }}
  BASE_IMAGE: ${{ inputs.baseImage }}

jobs:
  map_inputs:
    runs-on: ubuntu-latest
    outputs:
      baseImageTag: "${{ steps.step1.outputs.BASE_IMAGE_TAG }}"
      baseImageName: "${{ steps.step1.outputs.BASE_IMAGE_NAME }}"
      imageName: "${{ steps.step1.outputs.IMAGE_NAME }}"
      imageTag: "${{ steps.step1.outputs.IMAGE_TAG }}"
    steps:
      - id: step1
        run: |
          BASE_IMAGE_TAG=${BASE_IMAGE#*:};
          BASE_IMAGE_NAME=${BASE_IMAGE%%:*};
          case "$BASE_IMAGE_NAME" in
            nvidia/cuda) IMAGE_NAME=$GITHUB_REPOSITORY_OWNER/fastai;;
            *) echo >&2 "Error: unknown base image: $BASE_IMAGE_NAME"; exit 1;;
          esac;
          IMAGE_TAG=$BASE_IMAGE_TAG;
          printf "BASE_IMAGE_TAG=%q\n" "$BASE_IMAGE_TAG"   >> $GITHUB_OUTPUT;
          printf "BASE_IMAGE_NAME=%q\n" "$BASE_IMAGE_NAME" >> $GITHUB_OUTPUT;
          printf "IMAGE_NAME=%q\n" "$IMAGE_NAME"           >> $GITHUB_OUTPUT;
          printf "IMAGE_TAG=%q\n" "$IMAGE_TAG"             >> $GITHUB_OUTPUT;
          echo "### \`map_inputs\`"               >> $GITHUB_STEP_SUMMARY;
          echo "BASE_IMAGE=$BASE_IMAGE"           >> $GITHUB_STEP_SUMMARY;
          echo "BASE_IMAGE_TAG=$BASE_IMAGE_TAG"   >> $GITHUB_STEP_SUMMARY;
          echo "BASE_IMAGE_NAME=$BASE_IMAGE_NAME" >> $GITHUB_STEP_SUMMARY;
          echo "IMAGE_NAME=$IMAGE_NAME"           >> $GITHUB_STEP_SUMMARY;
          echo "IMAGE_TAG=$IMAGE_TAG"             >> $GITHUB_STEP_SUMMARY;
          echo ""                                 >> $GITHUB_STEP_SUMMARY;

  build-and-push-image:
    runs-on: ubuntu-latest
    needs: map_inputs
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ needs.map_inputs.outputs.imageName }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ needs.map_inputs.outputs.imageName }}:${{ needs.map_inputs.outputs.imageTag }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BASE_IMAGE=${{ env.BASE_IMAGE }}
